#+title:Emacs for Aero
#+author:Jade Michael Thornton

This project is a fork of GNU Emacs, used to build [[https://gitlab.com/thornjad/aero][Aero Emacs]]. This repository contains changes to core functionality which are neither approved nor peer reviewed by GNU, and as such is *NOT* considered stable.

** Installation
*** Manual install
The =INSTALL= file contains full installation information, but here's the synopsis:

#+begin_src sh
./autoconf.sh
./configure
make
make install
#+end_src

*** Docker
This is not considered stable, and not all features are currently working.

#+begin_src sh
make build-docker
docker run -ti --name emacs --net=host\
 -v /tmp/.X11-unix:/tmp/.X11-unix:ro -e DISPLAY="unix$DISPLAY"\
 -v <path_to_your_.emacs.d>:/home/aero/.config/emacs\
 -v <path_to_your_workspace>:/mnt/workspace\
 aero-emacs emacs
#+end_src

** License
Copyright (C) 2018-2021 Jade Michael Thornton\\
Copyright (C) 2001-2021 Free Software Foundation, Inc.

Aero Emacs is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation version 3.

*NOTICE*: While GNU Emacs may be licensed under either version 3 or any later version of the GPL, Aero Emacs is licensed under the terms of version 3 /only/. Version 3 is bad enough, I'm not letting it slip into some unknown future version automatically.

See the file =COPYING= for full license terms.
