#+title:Emacs for Aero
#+author:Jade Michael Thornton

This project is a fork of GNU Emacs, used to build [[https://gitlab.com/thornjad/aero][Aero Emacs]]. This repository contains changes to core functionality which are neither approved nor peer reviewed by GNU, and as such is *NOT* considered stable.

** Major differences with GNU Emacs
- Native compilation is enabled by default, providing significantly better performance over stock GNU Emacs
- Pure GTK implementation is available but disabled by default, eliminating reliance on X and supporting Wayland out of the box. Enable with =--with-pgtk=, must have GTK3+ available.
- Xwidgets support is enabled by default
- Included Dockerfile for containerized builds

** Installation
*** Manual install
The =INSTALL= file contains full installation information, but here's the synopsis:

#+begin_src sh
./autoconf.sh
./configure
make
make install
#+end_src

Before running =make=, it may be useful to check the output of =configure= to ensure the compiler will use all the features you want. You may be missing some optional dependencies.

Also note that =make= accepts a jobs argument, =-j=, which sets the number of threads the compiler can use. In theory, omitting this argument should give you a balance between fast-ish and not locking up the rest of your system. In practice, if you can give it the same number of threads as logical cores available, the process will go much quicker. On my 62-core system, =make= on its own takes around 2 minutes while =make -j16= runs in around 15 seconds.

*** Docker
This is not considered stable, and not all features are currently working.

#+begin_src sh
make build-docker
docker run -ti --name emacs --net=host\
 -v /tmp/.X11-unix:/tmp/.X11-unix:ro -e DISPLAY="unix$DISPLAY"\
 -v <path_to_your_.emacs.d>:/home/aero/.config/emacs\
 -v <path_to_your_workspace>:/mnt/workspace\
 aero-emacs emacs
#+end_src

** License
Copyright (C) 2018-2021 Jade Michael Thornton\\
Copyright (C) 1985-2021 Free Software Foundation, Inc.

Aero Emacs is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation version 3.

*NOTICE*: While GNU Emacs may be licensed under either version 3 or any later version of the GPL, Aero Emacs is licensed under the terms of version 3 /only/. Version 3 is bad enough, I'm not letting it slip into some unknown future version automatically.

See the file =COPYING= for full license terms.
